#!/bin/sh

${JAVA_HOME}/bin/java -server -cp ../../classes \
 -Dtests.frontend.FeatureExtractorTest.dumpTimes=true \
 -Dtests.frontend.FeatureExtractorTest.batchMode=true \
 tests.frontend.FeatureExtractorTest \
 FeatureExtractorTest \
 frontend.props.16k \
 batch.ctl
