#!/bin/sh

${JAVA_HOME}/bin/java -cp ../../classes \
 -Dtests.frontend.PreemphasizerTest.dumpTimes=true \
 tests.frontend.PreemphasizerTest \
 PreemphasizerTest \
 frontend.props.16k \
 19990601-114739-00000001.raw

${JAVA_HOME}/bin/java -cp ../../classes \
 -Dtests.frontend.HammingWindowerTest.dumpTimes=true \
 tests.frontend.HammingWindowerTest \
 HammingWindowerTest \
 frontend.props.16k \
 19990601-114739-00000001.raw

${JAVA_HOME}/bin/java -cp ../../classes \
 -Dtests.frontend.MelFilterbankTest.dumpTimes=true \
 tests.frontend.MelFilterbankTest \
 MelFilterbankTest \
 frontend.props.16k \
 19990601-114739-00000001.raw

${JAVA_HOME}/bin/java -cp ../../classes \
 -Dtests.frontend.MelCepstrumTest.dumpTimes=true \
 tests.frontend.MelCepstrumTest \
 MelCepstrumTest \
 frontend.props.16k \
 19990601-114739-00000001.raw

${JAVA_HOME}/bin/java -cp ../../classes \
 -Dtests.frontend.CmnFeatureExtractorTest.dumpTimes=true \
 tests.frontend.CmnFeatureExtractorTest cepstra.ctl
