# [[[copyright]]]

# Relative path to the "base" of the source tree
TOP = ..
PACKAGE_PATH = tests

# List any sub directories that need to be built.  Start with generic
# packages going toward specialized.  That is, if one package depends
# on another, put the dependent package later in the list.
SUBDIRS = frontend model search decoder

##########################################################################

include ${TOP}/build/Makefile.config
