# [[[copyright]]]

# Relative path to the "base" of the source tree
TOP = ../..
PACKAGE_PATH = tests/performance

# List any sub directories that need to be built.  Start with generic
# packages going toward specialized.  That is, if one package depends
# on another, put the dependent package later in the list.
SUBDIRS = an4 rm1 ti46 tidigits

##########################################################################

include ${TOP}/build/Makefile.config
