

all:
	echo "building all"
	echo "building all"
	echo "building all"
	echo "building all"
	sleep 3

all_fail:
	echo "building all"
	echo "building all"
	echo "building all"
	echo "building all"
	sleep 3
	another_bad_command


foo:
	cat test.dat

an4_words_unigram:
	cat an4_words_unigram.dat

an4_words_trigram:
	cat an4_words_trigram.dat


an4_words_fst:
	cat an4_words_fst.dat


an4_words_fail:
	cat an4_words_fst.dat
	ls /foo/bar

an4_words_total_fail:
	this_is_a_bad_command

an4_words:
	cat an4_words_fst.dat
