# [[[copyright]]]

# Relative path to the "base" of the source tree
TOP = ../..
PACKAGE_PATH = edu/cmu

# List any sub directories that need to be built.  Start with generic
# packages going toward specialized.  That is, if one package depends
# on another, put the dependent package later in the list.
SUBDIRS = sphinx

##########################################################################

include ${TOP}/build/Makefile.config
