#!/bin/sh

# Run Sphinx4 in batch mode
#
# Copyright (c) 2010 Carnegie Mellon University.


# Find Java
if [ -z "$JAVA_HOME" ]; then
    export JAVA_HOME=/usr/lib/jvm/default-java
fi
if [ -z "$JAVACMD" ]; then
    if [ -n "$JAVA_HOME" ]; then
	if [ -x "$JAVA_HOME/jre/bin/java" ]; then
	    JAVACMD="$JAVA_HOME/jre/bin/java"
	else
	    JAVACMD="$JAVA_HOME/bin/java"
	fi
    else
	JAVACMD=`which java 2>/dev/null`
	if [ -z "$JAVACMD" ]; then
	    JAVACMD=java
	fi
    fi
fi

if [ ! -x "$JAVACMD" ] ; then
    >&2 echo "Unable to locate Java virtual machine."
    >&2 echo "Tried: $JAVACMD"
    >&2 echo "Make sure \$JAVA_HOME is set properly."
    exit 1
fi

CLASSPATH="/usr/share/java/sphinx4.jar:/usr/share/java/sphinx4-batch.jar"
MAINCLASS="edu.cmu.sphinx.tools.batch.BatchModeRecognizer"

# Give it more memory if necessary (probably)
if [ "$1" = "--memsize" ]; then
    MEMORY="-Xmx$2"
    shift
    shift
fi

exec java $MEMORY -cp "$CLASSPATH" "$MAINCLASS" "$@"
