#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
#
# This script retrieves the sphinx4 history for a particular date
#
# usage: cvs_history date
#
# date should be in the form 2002-12-07 (YYYY-MM-DD)
#
scvs history -ac | grep sphinx4 | grep $*

