#!/bin/sh
# Copyright 1999-2007 Carnegie Mellon University.  
# Portions Copyright 2002-2007 Sun Microsystems, Inc.  
# Portions Copyright 2002-2007 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# Updates the log with all of the interim entries and puts it
# back into source control


logBase=regressionResults/regression.log
interimLog=interim.log

scvs checkout $logBase
cat $interimLog >> $logBase
scvs commit -m "regression_test" $logBase

# We only need the following uf we're ever able to update the mysql
# server at sf.net from command line programs, (as opposed to web
# browser based updates)

#srsync htdocs $logBase
#sshh '(cd /home/groups/c/cm/cmusphinx/cgi-bin/ && ./mysql_update_table.pl ~/'`basename $logBase`')'
