#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# Updates the log with all of the interim entries and puts it
# back into source control


logBase=regression.log
interimLog=interim.log

scvs update $logBase
cat $interimLog >> $logBase
scvs commit -m "regression_test" $logBase
