#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script generates a test summary report and mails it to the
# proper mailing list.
#
# To receive email reports about regression tests, add your email
# address to the list of recipients
#
# usage: mailReport

recipients="cmusphinx-results@lists.sourceforge.net"
#recipients="Paul.Lamere@sun.com"
./makeReport < regression.log | mailx -s "S4 regression test report" $recipients

