#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script generates and pushes the regression report to the web
#
# usage: pushReport

# To receive email reports about regression tests, add your email
# address to the list of recipients
#

# the 'dots' in the hostname can mess things up for the twik so
# lets just use the left most name

hostName=`./getHostname`

reportName=regression_report_$hostName.html

./makeWebpage < regression.log > $reportName
sscp $reportName
sshh mv $reportName /home/groups/c/cm/cmusphinx/htdocs
