#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi Electronic Research Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script generates and pushes the twiki reports
#

twikidir=/home/groups/c/cm/cmusphinx/twiki/data/Sphinx4

./makeTwikiReports IsolatedDigitsResults
./makeTwikiReports ConnectedDigitsResults
./makeTwikiReports SmallVocabResults
./makeTwikiReports MediumVocabResults

tar cf twikireports.tar AutoGen*.txt
sscp twikireports.tar
sshh '(cd /home/groups/c/cm/cmusphinx/twiki/data/Sphinx4; tar xf ~/twikireports.tar; chgrp cmusphinx `ls AutoGen*`;)'
