#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script generates the 'whats new' web page and pushes it to the
# web
#
# usage: pushChanges

# To receive email reports about regression tests, add your email
# address to the list of recipients
#


date=`cat .startDate`
./whatsNew $date > $date.html
sscp $date.html
sshh mv $date.html /home/groups/c/cm/cmusphinx/htdocs
sshh '(cd /home/groups/c/cm/cmusphinx/htdocs; chgrp -f cmusphinx `ls`; chmod -f g+w `ls`;)'
