#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script generates and pushes the test reports
#


./makeTestReports IsolatedDigitsResults
./makeTestReports ConnectedDigitsResults
./makeTestReports SmallVocabResults
./makeTestReports MediumVocabResults
./makeTestReports LargeVocabResults

tar cf testreports.tar AutoGen*.html
sscp testreports.tar
sshh '(cd /home/groups/c/cm/cmusphinx/htdocs/regressionReports; tar xf ~/testreports.tar; chgrp cmusphinx `ls AutoGen*`;)'
