#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script specifies the tests to run for the S4 regression tests
#
# each test should start with 'runTest'. The second field is a
# relative path from the regression test directory to the directory
# where the test should be run from,  The third field is the make
# target for the test.


./getTime >.startTime

./runTest ../performance/tidigits tidigits_quick  -Dskip=5 tidigits_wordlist

touch ./.testDone
