#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script specifies the tests to run for the S4 regression tests
#
# each test should start with 'runTest'. The second field is a
# relative path from the regression test directory to the directory
# where the test should be run from,  The third field is the make
# label for the test (the label that goes in the regression test
# log. The final fields are optional and if they exist are
# the targets for the make command. In their absence, the label
# is used as the target.  For most tests, the label and the target
# are the same, but for the _quick tests, the target is different.

# this is a set of standard tests that run every night.
# this should be restricted to run in about 4 hours

./getTime >.startTime

./runLiveTest ../performance/tidigits tidigits_wordlist_live_quick  -Dskip=5 tidigits_wordlist_live
./runLiveTest ../performance/an4 an4_words_bigram_live

touch ./.testDone

