#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi Electronic Research Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script specifies the tests to run for the S4 regression tests
#
# each test should start with 'runTest'. The second field is a
# relative path from the regression test directory to the directory
# where the test should be run from,  The third field is the make
# label for the test (the label that goes in the regression test
# log. The final fields are optional and if they exist are
# the targets for the make command. In their absence, the label
# is used as the target.  For most tests, the label and the target
# are the same, but for the _quick tests, the target is different.

# this is a set of standard tests that run every night.
# this should be restricted to run in about 4 hours

./getTime >.startTime

./runTest ../performance/ti46 ti46_wordlist
./runTest ../performance/ti46 ti46_flat_unigram
./runTest ../performance/ti46 ti46_flat_unigram_fst

./runTest ../performance/tidigits tidigits_wordlist_quick         MODE=quick tidigits_wordlist
./runTest ../performance/tidigits tidigits_flat_unigram_quick     MODE=quick tidigits_flat_unigram
./runTest ../performance/tidigits tidigits_flat_unigram_fst_quick MODE=quick tidigits_flat_unigram_fst

./runTest ../performance/an4 an4_words_wordlist
./runTest ../performance/an4 an4_words_unigram
./runTest ../performance/an4 an4_words_bigram
./runTest ../performance/an4 an4_words_unigram_fst
./runTest ../performance/an4 an4_words_bigram_fst
./runTest ../performance/an4 an4_words_trigram_fst

./runTest ../performance/rm1 rm1_bigram_quick            MODE=quick rm1_bigram
./runTest ../performance/rm1 rm1_trigram_quick           MODE=quick rm1_trigram

touch ./.testDone

# these tests have been retired in favor of the rm1 bigram and trigram tests
# ./runTest ../performance/an4 an4_words_flat_unigram
# ./runTest ../performance/an4 an4_words_flat_unigram_fst
