#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# Shows the NIST Align summary data for the given S4 output
#
s4_align $* | gawk '

$2 == "SUMMARY" {
  printOn = 1;
}

$1 == "CONFUSION" {
  printOn = 0;
}

{
    if (printOn) {
        print $0;
    }
}
'



