#!/bin/sh
# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi ElectricResearch Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
# This script performs the highlevel coordination for the regression
# tests which includes building S4, runnng the tests, logging the
# results, putting the results out to CVS and performing email
# notification

# Update log
#
# appends the standard input to the log, First, it makes sure that we
# have the latest copy of the log, updates the log and then checks it
# back in.
#
# Usage: updateLog < text


logBase=regression.log
interimLog=interim.log

cat >> $interimLog
