#!/usr/bin/perl
# This script collects the set of CVS changes for a particular date 
# and builds a web page for them. This script was originally going to
# be a CGI script which is why it is written in perl, but there were
# problems accessesing CVS anonymously from the web server, so it is
# now only run at build time.
#
# usage: whatsNew YYYY-MM-DD
#
#

sub getPreviousVersion {
    local($version) = @_;
    ($major, $minor) = split(/\./, $version);
    $newVersion = $major . "." . ($minor -1);
}

$queryDate = $ARGV[0];
$viewCVS = "http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/cmusphinx/";

print "Content-Type: text/html\n\n";
print "<html>\n";
print "<head>\n";
print "<title>Sphinx 4 Source Changes on $queryDate </title>\n";
print "</head>\n";
print "<body>\n";

print "<table cellpadding=0 cellspacing=0 border=0 width=100%\n";
print "    align=center bgcolor=#ccccff>\n";
print "<tbody>\n";
print "<tr>\n";
print "<td valign=top align=center><br>\n";
print "<big><big><b>Sphinx 4 Source Changes for $queryDate\n";
print "</b></big></big><br>\n";
print "<br>\n";
print "</td>\n";
print "</tr>\n";
print "</tbody>\n";
print "</table>\n";
print "<br>\n";
print "</div>\n";
print "<br>\n";


print "<br>\n";

#$cvs_history = "/usr/bin/cvs -d:pserver:anonymous\@cvs1:/cvsroot/cmusphinx history -ac";

$cvs_history_file = "cvs_history.gz";
$cvs_history = "gunzip -c $cvs_history_file";

open(HIST, "$cvs_history | ") or print "<p>Can't open cvs history.</p>";

# print start_table({-border=>''});
print "<table align=center cellpadding=2 cellspacing=2 border=1 width=80%>\n";

print "<tr align=CENTER,valign=TOP, bgcolor=#ccccff>\n";
print "<th> Path </th>\n";
print "<th> File </th>\n";
print "<th> Version </th>\n";
print "<th> Who </th>\n";

while (<HIST>) {
    next unless /sphinx4/;
    next unless /$queryDate/;
    ($op, $date, $time, $lines, $who, $version, $file, $path, $foo,
    $bar) = split(/\s+/, $_);
    $fullPath = $path . "/" . $file;
    $versionURL = $viewCVS . $path . "/" . $file . "?rev=" . $version . 
	 "&content-type=text/vnd.viewcvs-markup";

    $diffURL = $viewCVS . $path . "/" . $file . ".diff?r1=" . $version
        . "&r2=" . getPreviousVersion($version);

    if ($file ne "regression.log") {
	print "<tr align=left valign=top>\n";
	print "<td> $path </td>\n";
	print "<td> <a href=$versionURL>" . $file . "</a></td>\n"; 
	print "<td> <a href=$diffURL> $version</a> </td>\n";
	print "<td> $who </td>\n";
	print "</tr>\n";
    }
}

close(HIST);
unlink $passfile;

print "</table>\n";

print "<UL>\n";

$date_string = (stat($cvs_history_file))[9];
print  "<li> Includes checkins up to " . localtime($date_string);
if ((localtime($date_string))[8]) {
   print " PDT</li>\n";
} else {
   print " PST</li>\n";
}

print  "<li> Click File to show source code</li>\n";
print  "<li> Click Version to show changes made since last version</li>\n";
print "</UL>\n";


print "</body\n";
print "</html>\n";
